version: "3.9"
services:
  # Nuxt app
  frontend:
    container_name: "frontend"
    environment:
      - VIRTUAL_HOST=guillaume-prog.com

    build: .
    networks:
      - proxy_net

  # Pocketbase instance
  backend:
    container_name: "backend"
    environment:
      - VIRTUAL_HOST=admin.guillaume-prog.com

    image: "augustodelg/pocketbase"
    volumes:
      - data:/pb_data
    networks:
      - proxy_net

  # NGINX reverse proxy
  nginx-proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    ports:
      - 4080:80
      - 4443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - /usr/share/nginx/html
    networks:
      - proxy_net
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  # SSL cert generation
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: encrypt
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    networks:
      - proxy_net

  # SSL cert renewal
  certs:
    image: tutum/apache-php
    container_name: certs
    environment:
      - VIRTUAL_HOST=guillaume-prog.com,www.guillaume-prog.com
      - LETSENCRYPT_HOST=guillaume-prog.com,www.guillaume-prog.com
      - LETSENCRYPT_EMAIL=guillaume.roussin44@gmail.com
    networks:
      - cert_net

volumes:
  data:
  certs:

networks:
  proxy_net:
    driver: bridge
  cert_net:
    driver: bridge
